version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:sdk
    steps:
      - checkout
      - run:
          name: Build the projects
          command: |
            dotnet build -c Release
      - run:
          name: Run Unit Tests
          command: |
            cd src/tests/SoloX.ExpressionTools.Parser.UTest
            dotnet test -c Release --no-build
            cd ../../..

            cd src/tests/SoloX.ExpressionTools.Transform.UTest
            dotnet test -c Release --no-build
            cd ../../..
      - run:
          name: Run Code coverage
          command: |
            dotnet tool install coveralls.net --version 1.0.0 --tool-path coveralls

            cd src/tests/SoloX.ExpressionTools.Parser.UTest
            dotnet test -c Release --no-build -p:CollectCoverage=true -p:Exclude=\"[xunit.*]*,[SoloX.*.Sample]*,[SoloX.*.UTest]*\" -p:MergeWith="../../../result.coverlet.json" -p:CoverletOutput="../../../result.coverlet.json"
            cd ../../..

            cd src/tests/SoloX.ExpressionTools.Transform.UTest
            dotnet test -c Release --no-build -p:CollectCoverage=true -p:Exclude=\"[xunit.*]*,[SoloX.*.Sample]*,[SoloX.*.UTest]*\" -p:MergeWith="../../../result.coverlet.json" -p:CoverletOutput="../../../result.opencover.xml" -p:CoverletOutputFormat="opencover"
            cd ../../..

            mkdir coverage
            cp result.opencover.xml coverage/result.opencover.xml
            coveralls/csmacnz.Coveralls --opencover -i coverage/result.opencover.xml --repoToken $COVERALLS_REPO_TOKEN --useRelativePaths --commitId $CIRCLE_SHA1 --commitBranch $CIRCLE_BRANCH --commitAuthor $CIRCLE_USERNAME --jobId $CIRCLE_BUILD_NUM --serviceName circleci
      - store_artifacts:
          path: coverage
      - run:
          name: Generate packages
          command: |
            mkdir packages
            cd src/libs/SoloX.ExpressionTools.Parser
            dotnet pack -c Release --no-build
            cd ../../..
            mv src/libs/SoloX.ExpressionTools.Parser/bin/Release/*.nupkg packages/
            cd src/libs/SoloX.ExpressionTools.Transform
            dotnet pack -c Release --no-build
            cd ../../..
            mv src/libs/SoloX.ExpressionTools.Transform/bin/Release/*.nupkg packages/
      - store_artifacts:
          path: packages