version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:sdk
    steps:
      - checkout
      - run:
          name: Building the project
          command: dotnet build
      - run:
          name: Run Unit Tests
          command: dotnet test