name: Build - CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    uses: ./.github/workflows/build-dotnet.yml
    with:
      run-pack: true
      test-projects: >
        [
          "src/tests/SoloX.ExpressionTools.Parser.UTest",
          "src/tests/SoloX.ExpressionTools.Transform.UTest"
        ]
    secrets: inherit