name: Build - CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    uses: xaviersolau/devops-workflows/.github/workflows/build-dotnet.yml@v1.1.0
    with:
      run-pack: true
      test-projects: >
        [
          "src/tests/SoloX.ExpressionTools.Parser.UTest",
          "src/tests/SoloX.ExpressionTools.Transform.UTest"
        ]
