name: Build - PR

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    uses: ./.github/workflows/build-dotnet.yml
    with:
      test-projects: >
        [
          "src/tests/SoloX.ExpressionTools.Parser.UTest",
          "src/tests/SoloX.ExpressionTools.Transform.UTest"
        ]
    secrets: inherit